// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFH2mJ1paXyb5ZIHkcV-s-s-0ZeHd4vc0',
    appId: '1:941334309955:web:de0149a4bb9c49d1d038f6',
    messagingSenderId: '941334309955',
    projectId: 'instacrap-clone-2025',
    authDomain: 'instacrap-clone-2025.firebaseapp.com',
    storageBucket: 'instacrap-clone-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNPjZYQ_RlblPvn1fjVz_YJ4J696K7rA0',
    appId: '1:523781455819:android:7e509125dedd8a1c03004e',
    messagingSenderId: '523781455819',
    projectId: 'instabug2025',
    storageBucket: 'instabug2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNlql_5uzX9f8cj1t_oian5wRFMxTFaPs',
    appId: '1:523781455819:ios:e7f41cc014afe8dd03004e',
    messagingSenderId: '523781455819',
    projectId: 'instabug2025',
    storageBucket: 'instabug2025.firebasestorage.app',
    androidClientId: '523781455819-4qivpv1halspc7btf2v0d11fubs1fdvo.apps.googleusercontent.com',
    iosClientId: '523781455819-0b8ao2arg2t8igh1hpehpfubpn4j881f.apps.googleusercontent.com',
    iosBundleId: 'z1nl0x.corp.instacrapClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn8QKqjoZPtEkto6QTpCo2EQlGu7qa4G0',
    appId: '1:941334309955:ios:3f80d45941065f42d038f6',
    messagingSenderId: '941334309955',
    projectId: 'instacrap-clone-2025',
    storageBucket: 'instacrap-clone-2025.firebasestorage.app',
    iosBundleId: 'z1nl0x.corp.instacrapClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFH2mJ1paXyb5ZIHkcV-s-s-0ZeHd4vc0',
    appId: '1:941334309955:web:708283004bd3021ed038f6',
    messagingSenderId: '941334309955',
    projectId: 'instacrap-clone-2025',
    authDomain: 'instacrap-clone-2025.firebaseapp.com',
    storageBucket: 'instacrap-clone-2025.firebasestorage.app',
  );
}